name: Deploy static website to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout GitHub repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Configure AWS credentials using GitHub secrets
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-2   # MUST match your S3 bucket region

      # Step 3: Sync website files from GitHub to S3
      - name: Deploy files to S3
        run: |
          aws-region: ap-south-2
aws s3 sync . s3://practice-githubb --delete --exclude ".git/*" --exclude ".github/*"

